services:
  web:
    build: ./site
    ports:
      - '80:3000'
    volumes:
      - ../database.db:/app/database.db
      - /sys/bus/iio/devices/iio:device0/in_temp_input:/app/in_temp_input
    restart: always
  cron:
    build: ./cron
    volumes:
      - ../database.db:/app/database.db
      - /sys/bus/iio/devices/iio:device0/in_temp_input:/app/in_temp_input
