FROM node:lts-alpine

EXPOSE 3000
WORKDIR /app

COPY ./package.json /app/package.json
COPY ./site/package.json /app/site/package.json

RUN npm install

COPY ./site /app/site
COPY ./db /app/db

WORKDIR /app/site
RUN npm run build

CMD ["npm", "run", "start"]