FROM node:lts-alpine

EXPOSE 3000
WORKDIR /app/site

COPY ./package.json /app
RUN cd /app
RUN npm install

COPY ./site/package.json /app/site/package.json
RUN cd /app/site
RUN npm install

COPY ./site /app/site
COPY ./db /app/db

RUN npm run build

CMD ["npm", "run", "start"]